// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Tracing implementation internals
#include "verilated_vcd_c.h"
#include "VTopMain__Syms.h"


VL_ATTR_COLD void VTopMain___024root__trace_init_sub__TOP__0(VTopMain___024root* vlSelf, VerilatedVcd* tracep) {
    if (false && vlSelf) {}  // Prevent unused
    VTopMain__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    VTopMain___024root__trace_init_sub__TOP__0\n"); );
    // Init
    const int c = vlSymsp->__Vm_baseCode;
    // Body
    tracep->declBit(c+14,"clock", false,-1);
    tracep->declBit(c+15,"reset", false,-1);
    tracep->declQuad(c+16,"gpr_zero", false,-1, 63,0);
    tracep->declQuad(c+18,"gpr_ra", false,-1, 63,0);
    tracep->declQuad(c+20,"gpr_sp", false,-1, 63,0);
    tracep->declQuad(c+22,"gpr_gp", false,-1, 63,0);
    tracep->declQuad(c+24,"gpr_tp", false,-1, 63,0);
    tracep->declQuad(c+26,"gpr_t0", false,-1, 63,0);
    tracep->declQuad(c+28,"gpr_t1", false,-1, 63,0);
    tracep->declQuad(c+30,"gpr_t2", false,-1, 63,0);
    tracep->declQuad(c+32,"gpr_s0", false,-1, 63,0);
    tracep->declQuad(c+34,"gpr_s1", false,-1, 63,0);
    tracep->declQuad(c+36,"gpr_a0", false,-1, 63,0);
    tracep->declQuad(c+38,"gpr_a1", false,-1, 63,0);
    tracep->declQuad(c+40,"gpr_a2", false,-1, 63,0);
    tracep->declQuad(c+42,"gpr_a3", false,-1, 63,0);
    tracep->declQuad(c+44,"gpr_a4", false,-1, 63,0);
    tracep->declQuad(c+46,"gpr_a5", false,-1, 63,0);
    tracep->declQuad(c+48,"gpr_a6", false,-1, 63,0);
    tracep->declQuad(c+50,"gpr_a7", false,-1, 63,0);
    tracep->declQuad(c+52,"gpr_s2", false,-1, 63,0);
    tracep->declQuad(c+54,"gpr_s3", false,-1, 63,0);
    tracep->declQuad(c+56,"gpr_s4", false,-1, 63,0);
    tracep->declQuad(c+58,"gpr_s5", false,-1, 63,0);
    tracep->declQuad(c+60,"gpr_s6", false,-1, 63,0);
    tracep->declQuad(c+62,"gpr_s7", false,-1, 63,0);
    tracep->declQuad(c+64,"gpr_s8", false,-1, 63,0);
    tracep->declQuad(c+66,"gpr_s9", false,-1, 63,0);
    tracep->declQuad(c+68,"gpr_s10", false,-1, 63,0);
    tracep->declQuad(c+70,"gpr_s11", false,-1, 63,0);
    tracep->declQuad(c+72,"gpr_t3", false,-1, 63,0);
    tracep->declQuad(c+74,"gpr_t4", false,-1, 63,0);
    tracep->declQuad(c+76,"gpr_t5", false,-1, 63,0);
    tracep->declQuad(c+78,"gpr_t6", false,-1, 63,0);
    tracep->declQuad(c+80,"csrDebug_mstatus", false,-1, 63,0);
    tracep->declQuad(c+82,"csrDebug_mtvec", false,-1, 63,0);
    tracep->declQuad(c+84,"csrDebug_mepc", false,-1, 63,0);
    tracep->declQuad(c+86,"csrDebug_mcause", false,-1, 63,0);
    tracep->declBus(c+88,"debug_instr_instr", false,-1, 31,0);
    tracep->declQuad(c+89,"debug_commit_pc", false,-1, 63,0);
    tracep->declQuad(c+91,"debug_dynamic_pc", false,-1, 63,0);
    tracep->declBit(c+93,"debug_hazard_stallF", false,-1);
    tracep->declBit(c+94,"debug_hazard_stallD", false,-1);
    tracep->declBit(c+95,"debug_hazard_flushE", false,-1);
    tracep->declBus(c+96,"debug_hazard_hu_exu_ctrl_forwardA", false,-1, 1,0);
    tracep->declBus(c+97,"debug_hazard_hu_exu_ctrl_forwardB", false,-1, 1,0);
    tracep->declBus(c+98,"debug_hazard_hu_idu_ctrl_forwardA", false,-1, 1,0);
    tracep->declBus(c+99,"debug_hazard_hu_idu_ctrl_forwardB", false,-1, 1,0);
    tracep->declQuad(c+100,"debug_probe_data", false,-1, 63,0);
    tracep->declQuad(c+102,"debug_alu_data_E_data", false,-1, 63,0);
    tracep->declQuad(c+104,"debug_alu_data_W_data", false,-1, 63,0);
    tracep->declBus(c+106,"debug_forwardA_data", false,-1, 1,0);
    tracep->declBus(c+107,"debug_forwardB_data", false,-1, 1,0);
    tracep->declBus(c+108,"debug_forward_idu_A_data", false,-1, 1,0);
    tracep->declBus(c+109,"debug_forward_idu_B_data", false,-1, 1,0);
    tracep->declQuad(c+110,"debug_alu_srcA_data", false,-1, 63,0);
    tracep->declQuad(c+112,"debug_alu_srcB_data", false,-1, 63,0);
    tracep->declBus(c+114,"debug_rdD_data", false,-1, 4,0);
    tracep->declBus(c+115,"debug_rdE_data", false,-1, 4,0);
    tracep->declBus(c+116,"debug_rdM_data", false,-1, 4,0);
    tracep->declBus(c+117,"debug_rdW_data", false,-1, 4,0);
    tracep->declQuad(c+118,"pipelineTrace_if_id_pc_pc", false,-1, 63,0);
    tracep->declBus(c+120,"pipelineTrace_if_id_instr_instr", false,-1, 31,0);
    tracep->declBit(c+121,"pipelineTrace_if_id_pcEnable", false,-1);
    tracep->declQuad(c+122,"pipelineTrace_id_ex_pc_pc", false,-1, 63,0);
    tracep->declBus(c+124,"pipelineTrace_id_ex_instr_instr", false,-1, 31,0);
    tracep->declBit(c+125,"pipelineTrace_id_ex_pcEnable", false,-1);
    tracep->declQuad(c+126,"pipelineTrace_ex_ls_pc_pc", false,-1, 63,0);
    tracep->declBus(c+128,"pipelineTrace_ex_ls_instr_instr", false,-1, 31,0);
    tracep->declBit(c+129,"pipelineTrace_ex_ls_pcEnable", false,-1);
    tracep->declQuad(c+130,"pipelineTrace_ls_wb_pc_pc", false,-1, 63,0);
    tracep->declBus(c+132,"pipelineTrace_ls_wb_instr_instr", false,-1, 31,0);
    tracep->declBit(c+133,"pipelineTrace_ls_wb_pcEnable", false,-1);
    tracep->declQuad(c+134,"pipelineTrace_rf_pc_pc", false,-1, 63,0);
    tracep->declBus(c+136,"pipelineTrace_rf_instr_instr", false,-1, 31,0);
    tracep->declBit(c+137,"pipelineTrace_rf_pcEnable", false,-1);
    tracep->declQuad(c+138,"jumpTrace_dynamic_pc", false,-1, 63,0);
    tracep->declBit(c+140,"jumpTrace_instr_jump", false,-1);
    tracep->declBit(c+141,"jumpTrace_instr_branch", false,-1);
    tracep->declBit(c+142,"jumpTrace_instr_pcPlusSrc", false,-1);
    tracep->declBit(c+143,"jumpTrace_idu_pcSrc", false,-1);
    tracep->declQuad(c+144,"jumpTrace_bruSrcA", false,-1, 63,0);
    tracep->declQuad(c+146,"jumpTrace_bruSrcB", false,-1, 63,0);
    tracep->declBit(c+148,"jumpTrace_bruOutC", false,-1);
    tracep->declBus(c+149,"jumpTrace_bruCtrl", false,-1, 3,0);
    tracep->pushNamePrefix("TopMain ");
    tracep->declBit(c+14,"clock", false,-1);
    tracep->declBit(c+15,"reset", false,-1);
    tracep->declQuad(c+16,"gpr_zero", false,-1, 63,0);
    tracep->declQuad(c+18,"gpr_ra", false,-1, 63,0);
    tracep->declQuad(c+20,"gpr_sp", false,-1, 63,0);
    tracep->declQuad(c+22,"gpr_gp", false,-1, 63,0);
    tracep->declQuad(c+24,"gpr_tp", false,-1, 63,0);
    tracep->declQuad(c+26,"gpr_t0", false,-1, 63,0);
    tracep->declQuad(c+28,"gpr_t1", false,-1, 63,0);
    tracep->declQuad(c+30,"gpr_t2", false,-1, 63,0);
    tracep->declQuad(c+32,"gpr_s0", false,-1, 63,0);
    tracep->declQuad(c+34,"gpr_s1", false,-1, 63,0);
    tracep->declQuad(c+36,"gpr_a0", false,-1, 63,0);
    tracep->declQuad(c+38,"gpr_a1", false,-1, 63,0);
    tracep->declQuad(c+40,"gpr_a2", false,-1, 63,0);
    tracep->declQuad(c+42,"gpr_a3", false,-1, 63,0);
    tracep->declQuad(c+44,"gpr_a4", false,-1, 63,0);
    tracep->declQuad(c+46,"gpr_a5", false,-1, 63,0);
    tracep->declQuad(c+48,"gpr_a6", false,-1, 63,0);
    tracep->declQuad(c+50,"gpr_a7", false,-1, 63,0);
    tracep->declQuad(c+52,"gpr_s2", false,-1, 63,0);
    tracep->declQuad(c+54,"gpr_s3", false,-1, 63,0);
    tracep->declQuad(c+56,"gpr_s4", false,-1, 63,0);
    tracep->declQuad(c+58,"gpr_s5", false,-1, 63,0);
    tracep->declQuad(c+60,"gpr_s6", false,-1, 63,0);
    tracep->declQuad(c+62,"gpr_s7", false,-1, 63,0);
    tracep->declQuad(c+64,"gpr_s8", false,-1, 63,0);
    tracep->declQuad(c+66,"gpr_s9", false,-1, 63,0);
    tracep->declQuad(c+68,"gpr_s10", false,-1, 63,0);
    tracep->declQuad(c+70,"gpr_s11", false,-1, 63,0);
    tracep->declQuad(c+72,"gpr_t3", false,-1, 63,0);
    tracep->declQuad(c+74,"gpr_t4", false,-1, 63,0);
    tracep->declQuad(c+76,"gpr_t5", false,-1, 63,0);
    tracep->declQuad(c+78,"gpr_t6", false,-1, 63,0);
    tracep->declQuad(c+80,"csrDebug_mstatus", false,-1, 63,0);
    tracep->declQuad(c+82,"csrDebug_mtvec", false,-1, 63,0);
    tracep->declQuad(c+84,"csrDebug_mepc", false,-1, 63,0);
    tracep->declQuad(c+86,"csrDebug_mcause", false,-1, 63,0);
    tracep->declBus(c+88,"debug_instr_instr", false,-1, 31,0);
    tracep->declQuad(c+89,"debug_commit_pc", false,-1, 63,0);
    tracep->declQuad(c+91,"debug_dynamic_pc", false,-1, 63,0);
    tracep->declBit(c+93,"debug_hazard_stallF", false,-1);
    tracep->declBit(c+93,"debug_hazard_stallD", false,-1);
    tracep->declBit(c+93,"debug_hazard_flushE", false,-1);
    tracep->declBus(c+96,"debug_hazard_hu_exu_ctrl_forwardA", false,-1, 1,0);
    tracep->declBus(c+97,"debug_hazard_hu_exu_ctrl_forwardB", false,-1, 1,0);
    tracep->declBus(c+98,"debug_hazard_hu_idu_ctrl_forwardA", false,-1, 1,0);
    tracep->declBus(c+99,"debug_hazard_hu_idu_ctrl_forwardB", false,-1, 1,0);
    tracep->declQuad(c+100,"debug_probe_data", false,-1, 63,0);
    tracep->declQuad(c+102,"debug_alu_data_E_data", false,-1, 63,0);
    tracep->declQuad(c+104,"debug_alu_data_W_data", false,-1, 63,0);
    tracep->declBus(c+96,"debug_forwardA_data", false,-1, 1,0);
    tracep->declBus(c+97,"debug_forwardB_data", false,-1, 1,0);
    tracep->declBus(c+98,"debug_forward_idu_A_data", false,-1, 1,0);
    tracep->declBus(c+99,"debug_forward_idu_B_data", false,-1, 1,0);
    tracep->declQuad(c+110,"debug_alu_srcA_data", false,-1, 63,0);
    tracep->declQuad(c+112,"debug_alu_srcB_data", false,-1, 63,0);
    tracep->declBus(c+114,"debug_rdD_data", false,-1, 4,0);
    tracep->declBus(c+115,"debug_rdE_data", false,-1, 4,0);
    tracep->declBus(c+116,"debug_rdM_data", false,-1, 4,0);
    tracep->declBus(c+117,"debug_rdW_data", false,-1, 4,0);
    tracep->declQuad(c+118,"pipelineTrace_if_id_pc_pc", false,-1, 63,0);
    tracep->declBus(c+120,"pipelineTrace_if_id_instr_instr", false,-1, 31,0);
    tracep->declBit(c+121,"pipelineTrace_if_id_pcEnable", false,-1);
    tracep->declQuad(c+122,"pipelineTrace_id_ex_pc_pc", false,-1, 63,0);
    tracep->declBus(c+124,"pipelineTrace_id_ex_instr_instr", false,-1, 31,0);
    tracep->declBit(c+125,"pipelineTrace_id_ex_pcEnable", false,-1);
    tracep->declQuad(c+126,"pipelineTrace_ex_ls_pc_pc", false,-1, 63,0);
    tracep->declBus(c+128,"pipelineTrace_ex_ls_instr_instr", false,-1, 31,0);
    tracep->declBit(c+129,"pipelineTrace_ex_ls_pcEnable", false,-1);
    tracep->declQuad(c+89,"pipelineTrace_ls_wb_pc_pc", false,-1, 63,0);
    tracep->declBus(c+88,"pipelineTrace_ls_wb_instr_instr", false,-1, 31,0);
    tracep->declBit(c+133,"pipelineTrace_ls_wb_pcEnable", false,-1);
    tracep->declQuad(c+134,"pipelineTrace_rf_pc_pc", false,-1, 63,0);
    tracep->declBus(c+136,"pipelineTrace_rf_instr_instr", false,-1, 31,0);
    tracep->declBit(c+137,"pipelineTrace_rf_pcEnable", false,-1);
    tracep->declQuad(c+91,"jumpTrace_dynamic_pc", false,-1, 63,0);
    tracep->declBit(c+140,"jumpTrace_instr_jump", false,-1);
    tracep->declBit(c+141,"jumpTrace_instr_branch", false,-1);
    tracep->declBit(c+142,"jumpTrace_instr_pcPlusSrc", false,-1);
    tracep->declBit(c+143,"jumpTrace_idu_pcSrc", false,-1);
    tracep->declQuad(c+144,"jumpTrace_bruSrcA", false,-1, 63,0);
    tracep->declQuad(c+146,"jumpTrace_bruSrcB", false,-1, 63,0);
    tracep->declBit(c+148,"jumpTrace_bruOutC", false,-1);
    tracep->declBus(c+149,"jumpTrace_bruCtrl", false,-1, 3,0);
    tracep->declQuad(c+9,"rPC", false,-1, 63,0);
    tracep->declQuad(c+11,"rNPC", false,-1, 63,0);
    tracep->declBit(c+13,"rNPCValid", false,-1);
    tracep->declQuad(c+91,"npc", false,-1, 63,0);
    tracep->declQuad(c+1,"pc_rf_pc", false,-1, 63,0);
    tracep->declBus(c+3,"instr_rf_instr", false,-1, 31,0);
    tracep->declBit(c+4,"pcEnable_if_id", false,-1);
    tracep->declBit(c+5,"pcEnable_id_ex", false,-1);
    tracep->declBit(c+6,"pcEnable_ex_ls", false,-1);
    tracep->declBit(c+7,"pcEnable_ls_wb", false,-1);
    tracep->declBit(c+8,"pcEnable_rf", false,-1);
    tracep->pushNamePrefix("_Arbiter ");
    tracep->popNamePrefix(1);
    tracep->pushNamePrefix("_EXU ");
    tracep->pushNamePrefix("alu ");
    tracep->popNamePrefix(2);
    tracep->pushNamePrefix("_EX_LS ");
    tracep->pushNamePrefix("unnamedblk1 ");
    tracep->popNamePrefix(2);
    tracep->pushNamePrefix("_HU ");
    tracep->popNamePrefix(1);
    tracep->pushNamePrefix("_ID_EX ");
    tracep->pushNamePrefix("unnamedblk1 ");
    tracep->popNamePrefix(2);
    tracep->pushNamePrefix("_IF_ID ");
    tracep->pushNamePrefix("unnamedblk1 ");
    tracep->popNamePrefix(2);
    tracep->pushNamePrefix("_LSU ");
    tracep->popNamePrefix(1);
    tracep->pushNamePrefix("_LS_WB ");
    tracep->pushNamePrefix("unnamedblk1 ");
    tracep->popNamePrefix(2);
    tracep->pushNamePrefix("_T ");
    tracep->pushNamePrefix("bru ");
    tracep->popNamePrefix(1);
    tracep->pushNamePrefix("csrf ");
    tracep->pushNamePrefix("unnamedblk1 ");
    tracep->popNamePrefix(1);
    tracep->pushNamePrefix("unnamedblk2 ");
    tracep->popNamePrefix(2);
    tracep->pushNamePrefix("id ");
    tracep->popNamePrefix(1);
    tracep->pushNamePrefix("rf ");
    tracep->pushNamePrefix("unnamedblk1 ");
    tracep->popNamePrefix(1);
    tracep->pushNamePrefix("unnamedblk2 ");
    tracep->popNamePrefix(3);
    tracep->pushNamePrefix("_TP_SRAM ");
    tracep->pushNamePrefix("mem ");
    tracep->popNamePrefix(1);
    tracep->pushNamePrefix("unnamedblk1 ");
    tracep->popNamePrefix(2);
    tracep->pushNamePrefix("_T_3 ");
    tracep->popNamePrefix(1);
    tracep->pushNamePrefix("_WBU ");
    tracep->popNamePrefix(1);
    tracep->pushNamePrefix("unnamedblk1 ");
    tracep->popNamePrefix(2);
}

VL_ATTR_COLD void VTopMain___024root__trace_init_top(VTopMain___024root* vlSelf, VerilatedVcd* tracep) {
    if (false && vlSelf) {}  // Prevent unused
    VTopMain__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    VTopMain___024root__trace_init_top\n"); );
    // Body
    VTopMain___024root__trace_init_sub__TOP__0(vlSelf, tracep);
}

VL_ATTR_COLD void VTopMain___024root__trace_full_top_0(void* voidSelf, VerilatedVcd::Buffer* bufp);
void VTopMain___024root__trace_chg_top_0(void* voidSelf, VerilatedVcd::Buffer* bufp);
void VTopMain___024root__trace_cleanup(void* voidSelf, VerilatedVcd* /*unused*/);

VL_ATTR_COLD void VTopMain___024root__trace_register(VTopMain___024root* vlSelf, VerilatedVcd* tracep) {
    if (false && vlSelf) {}  // Prevent unused
    VTopMain__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    VTopMain___024root__trace_register\n"); );
    // Body
    tracep->addFullCb(&VTopMain___024root__trace_full_top_0, vlSelf);
    tracep->addChgCb(&VTopMain___024root__trace_chg_top_0, vlSelf);
    tracep->addCleanupCb(&VTopMain___024root__trace_cleanup, vlSelf);
}

VL_ATTR_COLD void VTopMain___024root__trace_full_sub_0(VTopMain___024root* vlSelf, VerilatedVcd::Buffer* bufp);

VL_ATTR_COLD void VTopMain___024root__trace_full_top_0(void* voidSelf, VerilatedVcd::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    VTopMain___024root__trace_full_top_0\n"); );
    // Init
    VTopMain___024root* const __restrict vlSelf VL_ATTR_UNUSED = static_cast<VTopMain___024root*>(voidSelf);
    VTopMain__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    // Body
    VTopMain___024root__trace_full_sub_0((&vlSymsp->TOP), bufp);
}

VL_ATTR_COLD void VTopMain___024root__trace_full_sub_0(VTopMain___024root* vlSelf, VerilatedVcd::Buffer* bufp) {
    if (false && vlSelf) {}  // Prevent unused
    VTopMain__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    VTopMain___024root__trace_full_sub_0\n"); );
    // Init
    uint32_t* const oldp VL_ATTR_UNUSED = bufp->oldp(vlSymsp->__Vm_baseCode);
    // Body
    bufp->fullQData(oldp+1,(vlSelf->TopMain__DOT__pc_rf_pc),64);
    bufp->fullIData(oldp+3,(vlSelf->TopMain__DOT__instr_rf_instr),32);
    bufp->fullBit(oldp+4,(vlSelf->TopMain__DOT__pcEnable_if_id));
    bufp->fullBit(oldp+5,(vlSelf->TopMain__DOT__pcEnable_id_ex));
    bufp->fullBit(oldp+6,(vlSelf->TopMain__DOT__pcEnable_ex_ls));
    bufp->fullBit(oldp+7,(vlSelf->TopMain__DOT__pcEnable_ls_wb));
    bufp->fullBit(oldp+8,(vlSelf->TopMain__DOT__pcEnable_rf));
    bufp->fullQData(oldp+9,(vlSelf->TopMain__DOT__rPC),64);
    bufp->fullQData(oldp+11,(vlSelf->TopMain__DOT__rNPC),64);
    bufp->fullBit(oldp+13,(vlSelf->TopMain__DOT__rNPCValid));
    bufp->fullBit(oldp+14,(vlSelf->clock));
    bufp->fullBit(oldp+15,(vlSelf->reset));
    bufp->fullQData(oldp+16,(vlSelf->gpr_zero),64);
    bufp->fullQData(oldp+18,(vlSelf->gpr_ra),64);
    bufp->fullQData(oldp+20,(vlSelf->gpr_sp),64);
    bufp->fullQData(oldp+22,(vlSelf->gpr_gp),64);
    bufp->fullQData(oldp+24,(vlSelf->gpr_tp),64);
    bufp->fullQData(oldp+26,(vlSelf->gpr_t0),64);
    bufp->fullQData(oldp+28,(vlSelf->gpr_t1),64);
    bufp->fullQData(oldp+30,(vlSelf->gpr_t2),64);
    bufp->fullQData(oldp+32,(vlSelf->gpr_s0),64);
    bufp->fullQData(oldp+34,(vlSelf->gpr_s1),64);
    bufp->fullQData(oldp+36,(vlSelf->gpr_a0),64);
    bufp->fullQData(oldp+38,(vlSelf->gpr_a1),64);
    bufp->fullQData(oldp+40,(vlSelf->gpr_a2),64);
    bufp->fullQData(oldp+42,(vlSelf->gpr_a3),64);
    bufp->fullQData(oldp+44,(vlSelf->gpr_a4),64);
    bufp->fullQData(oldp+46,(vlSelf->gpr_a5),64);
    bufp->fullQData(oldp+48,(vlSelf->gpr_a6),64);
    bufp->fullQData(oldp+50,(vlSelf->gpr_a7),64);
    bufp->fullQData(oldp+52,(vlSelf->gpr_s2),64);
    bufp->fullQData(oldp+54,(vlSelf->gpr_s3),64);
    bufp->fullQData(oldp+56,(vlSelf->gpr_s4),64);
    bufp->fullQData(oldp+58,(vlSelf->gpr_s5),64);
    bufp->fullQData(oldp+60,(vlSelf->gpr_s6),64);
    bufp->fullQData(oldp+62,(vlSelf->gpr_s7),64);
    bufp->fullQData(oldp+64,(vlSelf->gpr_s8),64);
    bufp->fullQData(oldp+66,(vlSelf->gpr_s9),64);
    bufp->fullQData(oldp+68,(vlSelf->gpr_s10),64);
    bufp->fullQData(oldp+70,(vlSelf->gpr_s11),64);
    bufp->fullQData(oldp+72,(vlSelf->gpr_t3),64);
    bufp->fullQData(oldp+74,(vlSelf->gpr_t4),64);
    bufp->fullQData(oldp+76,(vlSelf->gpr_t5),64);
    bufp->fullQData(oldp+78,(vlSelf->gpr_t6),64);
    bufp->fullQData(oldp+80,(vlSelf->csrDebug_mstatus),64);
    bufp->fullQData(oldp+82,(vlSelf->csrDebug_mtvec),64);
    bufp->fullQData(oldp+84,(vlSelf->csrDebug_mepc),64);
    bufp->fullQData(oldp+86,(vlSelf->csrDebug_mcause),64);
    bufp->fullIData(oldp+88,(vlSelf->debug_instr_instr),32);
    bufp->fullQData(oldp+89,(vlSelf->debug_commit_pc),64);
    bufp->fullQData(oldp+91,(vlSelf->debug_dynamic_pc),64);
    bufp->fullBit(oldp+93,(vlSelf->debug_hazard_stallF));
    bufp->fullBit(oldp+94,(vlSelf->debug_hazard_stallD));
    bufp->fullBit(oldp+95,(vlSelf->debug_hazard_flushE));
    bufp->fullCData(oldp+96,(vlSelf->debug_hazard_hu_exu_ctrl_forwardA),2);
    bufp->fullCData(oldp+97,(vlSelf->debug_hazard_hu_exu_ctrl_forwardB),2);
    bufp->fullCData(oldp+98,(vlSelf->debug_hazard_hu_idu_ctrl_forwardA),2);
    bufp->fullCData(oldp+99,(vlSelf->debug_hazard_hu_idu_ctrl_forwardB),2);
    bufp->fullQData(oldp+100,(vlSelf->debug_probe_data),64);
    bufp->fullQData(oldp+102,(vlSelf->debug_alu_data_E_data),64);
    bufp->fullQData(oldp+104,(vlSelf->debug_alu_data_W_data),64);
    bufp->fullCData(oldp+106,(vlSelf->debug_forwardA_data),2);
    bufp->fullCData(oldp+107,(vlSelf->debug_forwardB_data),2);
    bufp->fullCData(oldp+108,(vlSelf->debug_forward_idu_A_data),2);
    bufp->fullCData(oldp+109,(vlSelf->debug_forward_idu_B_data),2);
    bufp->fullQData(oldp+110,(vlSelf->debug_alu_srcA_data),64);
    bufp->fullQData(oldp+112,(vlSelf->debug_alu_srcB_data),64);
    bufp->fullCData(oldp+114,(vlSelf->debug_rdD_data),5);
    bufp->fullCData(oldp+115,(vlSelf->debug_rdE_data),5);
    bufp->fullCData(oldp+116,(vlSelf->debug_rdM_data),5);
    bufp->fullCData(oldp+117,(vlSelf->debug_rdW_data),5);
    bufp->fullQData(oldp+118,(vlSelf->pipelineTrace_if_id_pc_pc),64);
    bufp->fullIData(oldp+120,(vlSelf->pipelineTrace_if_id_instr_instr),32);
    bufp->fullBit(oldp+121,(vlSelf->pipelineTrace_if_id_pcEnable));
    bufp->fullQData(oldp+122,(vlSelf->pipelineTrace_id_ex_pc_pc),64);
    bufp->fullIData(oldp+124,(vlSelf->pipelineTrace_id_ex_instr_instr),32);
    bufp->fullBit(oldp+125,(vlSelf->pipelineTrace_id_ex_pcEnable));
    bufp->fullQData(oldp+126,(vlSelf->pipelineTrace_ex_ls_pc_pc),64);
    bufp->fullIData(oldp+128,(vlSelf->pipelineTrace_ex_ls_instr_instr),32);
    bufp->fullBit(oldp+129,(vlSelf->pipelineTrace_ex_ls_pcEnable));
    bufp->fullQData(oldp+130,(vlSelf->pipelineTrace_ls_wb_pc_pc),64);
    bufp->fullIData(oldp+132,(vlSelf->pipelineTrace_ls_wb_instr_instr),32);
    bufp->fullBit(oldp+133,(vlSelf->pipelineTrace_ls_wb_pcEnable));
    bufp->fullQData(oldp+134,(vlSelf->pipelineTrace_rf_pc_pc),64);
    bufp->fullIData(oldp+136,(vlSelf->pipelineTrace_rf_instr_instr),32);
    bufp->fullBit(oldp+137,(vlSelf->pipelineTrace_rf_pcEnable));
    bufp->fullQData(oldp+138,(vlSelf->jumpTrace_dynamic_pc),64);
    bufp->fullBit(oldp+140,(vlSelf->jumpTrace_instr_jump));
    bufp->fullBit(oldp+141,(vlSelf->jumpTrace_instr_branch));
    bufp->fullBit(oldp+142,(vlSelf->jumpTrace_instr_pcPlusSrc));
    bufp->fullBit(oldp+143,(vlSelf->jumpTrace_idu_pcSrc));
    bufp->fullQData(oldp+144,(vlSelf->jumpTrace_bruSrcA),64);
    bufp->fullQData(oldp+146,(vlSelf->jumpTrace_bruSrcB),64);
    bufp->fullBit(oldp+148,(vlSelf->jumpTrace_bruOutC));
    bufp->fullCData(oldp+149,(vlSelf->jumpTrace_bruCtrl),4);
}
